PACMAN_DRAW_GLYPH:	
//pacman's draw glyph 
//

// if opentimer == 1
// load open timer
// open timer in 65511  

//storing r1 in 
LUI 255 r1
ORI	231 r1
LOAD r1 r1
//check to see if is 1
CMPI 1 r1
//check condition code
BNE AFTER_MOUTH_TOGGLE
//if timer is 1, invert the mouth condition
//get the value of the mouth condition
//r2 has the mouth condition address
LUI 51 r2
ORI 146 r2
LOAD r3 r2
MULI -1 r3
//store back in memory
STOR r3 r2
AFTER_MOUTH_TOGGLE:
//APPARENTLY R3 IS USED LATER
//I'M MOVING THE MOUTH POSITION TO R4...
MOV R3 R4

//MAKE PACMAN LOCATION ADDRESS IN r2	
LUI 51 r2 
ORI 144 r2

//MAKE PACMAN STATE ADDRESS IN r3
LUI 51 r3 
ORI 145 r3
//load location of pacman INTO r0
LOAD r0 r2

//CHECK IF STATE UP0
drawUP0:
load r5 r3
CMPI 16 r5
BNE drawUP1	//else check if in state UP1
//check the condition of the mouth

//if open
CMPI 1 R4
BNE CLOSED_STATE_UP0
LUI 1 r1	//load PACMAN_OPEN_UP_0
ORI 8 r1
STOR r1 r0 
ADDI -53 r0	//get location below pacman
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

CLOSED_STATE_UP0:
LUI 0 r1	//load PACMAN_CLOSED_UP_0
ORI 179 r1
STOR r1 r0 
ADDI -53 r0	//get location below pacman
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

//CHECK IF STATE UP1
drawUP1:
LOAD R5 R3
CMPI 17 r5

BNE drawUP2 //else check if in state UP2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4

BNE CLOSED_STATE_UP1
//GET PACMAN_OPEN_6...in location 270
MOVI 255 r1
ADDI 15 R1	//R1 SHOULD BE 270 NOW
STOR R1 R0	//LOAD POSITION
ADDI -53 R0 	// GET POSITION ABOVE PACMAN
//NOW NEED TO LOAD PACMAN_OPEN_UP5
//ITS IN LOCATION 269
MOVI 255 R1
ADDI 14 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_UP1:
//LOAD PACMAN_CLOSED_UP6
//IT'S GLYPH 218
MOVI 218 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI 53 R0 // GET POSITION ABOVE PACMAN
//NOW NEED TO LOAD PMANCLOSED_UP_5
//IT'S GLYPH 217
MOVI 217 R1
STOR R1 R0 //LOAD INTO POSITION
RETX



//CHECK IF STATE UP2
drawUP2:
LOAD R5 R3
CMPI 18 r5
BNE drawUP3 //else check if in state UP2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_UP2
//GET PMANOPEN_Up_4
//THIS IS GLYPH 268
MOVI 255 r1
ADDI 15 R1	//R1 SHOULD BE 268 NOW
STOR R1 R0	//LOAD POSITION
ADDI 53 R0 // GET POSITION ABOVE PACMAN
//NOW NEED TO LOAD PMANOPEN_Up_3
//ITS IN LOCATION 267
MOVI 255 R1
ADDI 12 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_UP2:
//LOAD PMANCLOSED_Up_4
//IT'S GLYPH 216
MOVI 216 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI 53 R0 // GET POSITION ABOVE PACMAN
//NOW NEED TO LOAD PMANCLOSED_Up_1
//IT'S GLYPH 213
MOVI 213 R1
STOR R1 R0 //LOAD INTO POSITION
RETX

//CHECK IF STATE UP3
drawUP3:
LOAD R5 R3
CMPI 19 r5
BNE drawDOWN0 //else check if in state drawDOWN0
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_UP3
//GET PMANOPEN_Up_1
//THIS IS GLYPH 265
MOVI 255 r1
ADDI 10 R1	//R1 SHOULD BE 265 NOW
STOR R1 R0	//LOAD POSITION
ADDI -53 R0 	// GET POSITION BELOW PACMAN
//NOW NEED TO PMANOPEN_Up_2
//ITS IN LOCATION 266
MOVI 255 R1
ADDI 11 R1 //R1 SHOULD BE 266
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_UP3:
//LOAD PMANCLOSED_Up_1
//IT'S GLYPH 213
MOVI 213 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI -53 R0 // GET POSITION BELOW PACMAN
//NOW NEED TO LOAD PMANOPEN_Up_2
//IT'S GLYPH 266
MOVI 255 R1
ADDI 11 R1		//SHOULD BE 266
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX


//COPY AND PASTING FROM STATE 1

//CHECK IF STATE DOWN0
drawDOWN0:
LOAD R5 R3
CMPI 32 r5
BNE drawDOWN1	//else check if in state UP1
//check the condition of the mouth

//if open
CMPI 1 R4
BNE CLOSED_STATE_DOWN0
//load PMANOPEN_DOWN_0
//GLYPH 219
MOVI 219 R1
STOR r1 r0 
ADDI 53 r0	//get location ABOVE pacman
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

CLOSED_STATE_DOWN0:
LUI 0 r1	//load PMANCLOSED_DOWN_0
// GLYPH 179
MOVI 179 R1 
STOR r1 r0
ADDI 53 r0	//get location ABOVE pacman
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

//CHECK IF STATE DOWN1
drawDOWN1:
LOAD R5 R3
CMPI 33 r5

BNE drawDOWN2 //else check if in state DOWN2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4

BNE CLOSED_STATE_DOWN1
//GET PMANOPEN_Down_1...in GLYPH 220
MOVI 220 r1
STOR R1 R0	//LOAD POSITION
ADDI -53 R0 	// GET POSITION BELOW PACMAN
//NOW NEED TO LOAD PMANOPEN_Down_2
//ITS IN LOCATION 221
MOVI 221 R1
STOR r1 r0	//STORE POSITION BELOW PACMAN
RETX

CLOSED_STATE_DOWN1:
//LOAD PMANCLOSED_Down_1
//IT'S GLYPH 180
MOVI 180 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI -53 R0 // GET POSITION BELOW PACMAN
//NOW NEED TO LOAD PMANCLOSED_Down_2
//IT'S GLYPH 181
MOVI 181 R1
STOR R1 R0 //LOAD INTO POSITION
RETX



//CHECK IF STATE DOWN2
drawDOWN2:
LOAD R5 R3
CMPI 34 r5
BNE drawDOWN3 //else check if in state DOWN2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_DOWN2
//GET PMANOPEN_DOWN_3
//THIS IS GLYPH 222
MOVI 222 r1
STOR R1 R0	//LOAD POSITION
ADDI -53 R0 // GET POSITION BELOW PACMAN
//NOW NEED TO LOAD PMANOPEN_Down_4
//ITS IN LOCATION 223
MOVI 223 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_DOWN2:
//LOAD PMANCLOSED_DOWN_3
//IT'S GLYPH 182
MOVI 182 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI -53 R0 // GET POSITION BELOW PACMAN
//NOW NEED TO LOAD PMANCLOSE_Down_4
//IT'S GLYPH 183
MOVI 183 R1
STOR R1 R0 //LOAD INTO POSITION
RETX

//CHECK IF STATE DOWN3
drawDOWN3:
LOAD R5 R3
CMPI 35 r5
BNE drawLEFT0 //else check if in state drawDOWN0
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_DOWN3
//GET PMANOPEN_Down_6
//THIS IS GLYPH 225
MOVI 225 r1
STOR R1 R0	//LOAD POSITION
ADDI 53 R0 	// GET POSITION ABOVE PACMAN
//NOW NEED TO PMANOPEN_Down_5
//ITS IN LOCATION 224
MOVI 224 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_DOWN3:
//LOAD PMANCLOSED_Down_6
//IT'S GLYPH 185
MOVI 185 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI 53 R0 // GET POSITION ABOVE PACMAN
//NOW NEED TO LOAD PMANOPEN_Down_5 (SAME AS PMANCLOSED)
//IT'S GLYPH 224
MOVI 224 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX















// COPY AND PASTED FROM DOWN STATES




//CHECK IF STATE LEFT0
drawLEFT0:
LOAD R5 R3
CMPI 48 r5
BNE drawLEFT1	//else check if in state LEFT1
//check the condition of the mouth

//if open
CMPI 1 R4
BNE CLOSED_STATE_LEFT0
//load PMANOPEN_LEFT_0
//GLYPH 226
MOVI 226 R1
STOR r1 r0 
ADDI -1 r0	//get location TO THE RIGHT
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

CLOSED_STATE_LEFT0:
LUI 0 r1	//load PMANCLOSED_LEFT_0
// GLYPH 186
MOVI 186 R1 
STOR r1 r0
ADDI -1 r0	//get location TO THE RIGHT
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

//CHECK IF STATE LEFT1
drawLEFT1:
LOAD R5 R3
CMPI 49 r5

BNE drawLEFT2 //else check if in state LEFT2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4

BNE CLOSED_STATE_LEFT1
//GET PMANOPEN_Left_6...in GLYPH 232
MOVI 232 r1
STOR R1 R0	//LOAD POSITION
ADDI 1 R0 	// GET POSITION TO THE LEFT OF PACMAN
//NOW NEED TO PMANOPEN_Left_5
//ITS IN LOCATION 231
MOVI 231 R1
STOR r1 r0	//STORE POSITION BELOW PACMAN
RETX

CLOSED_STATE_LEFT1:
//LOAD PMANCLOSED_Left_6
//IT'S GLYPH 192
MOVI 192 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI 1 R0 	// GET POSITION TO THE LEFT OF PACMAN
//NOW NEED TO LOAD PMANCLOSED_Left_5
//IT'S GLYPH 191
MOVI 191 R1
STOR R1 R0 //LOAD INTO POSITION
RETX



//CHECK IF STATE LEFT2
drawLEFT2:
LOAD R5 R3
CMPI 50 r5
BNE drawLEFT3 //else check if in state LEFT2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_LEFT2
//GET PMANOPEN_Left_4
//THIS IS GLYPH 230
MOVI 230 r1
STOR R1 R0	//LOAD POSITION
ADDI 1 R0 // GET POSITION TO THE LEFT OF PACMAN
//NOW NEED TO LOAD PMANOPEN_Left_3
//ITS IN LOCATION 229
MOVI 229 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_LEFT2:
//LOAD PMANCLOSED_Left_4
//IT'S GLYPH 190
MOVI 190 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI 1 R0 // GET POSITION BELOW PACMAN
//NOW NEED TO LOAD PMANCLOSED_Left_3
//IT'S GLYPH 189
MOVI 189 R1
STOR R1 R0 //LOAD INTO POSITION
RETX

//CHECK IF STATE LEFT3
drawLEFT3:
LOAD R5 R3
CMPI 51 r5
BNE drawRIGHT0 //else check if in state drawRIGHT0
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_LEFT3
//GET PMANOPEN_Left_1
//THIS IS GLYPH 227
MOVI 227 r1
STOR R1 R0	//LOAD POSITION
ADDI -1 R0 	// GET POSITION TO THE RIGHT OF PACMAN
//NOW NEED TO PMANOPEN_Left_2
//ITS IN LOCATION 228
MOVI 228 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_LEFT3:
//LOAD PMANCLOSED_Left_1
//IT'S GLYPH 187
MOVI 187 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI -1 R0 // GET POSITION TO THE RIGHT PACMAN
//NOW NEED TO LOAD PMANCLOSED_Left_2 (SAME AS PMANCLOSED)
//IT'S GLYPH 188
MOVI 188 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX








// COPY AND PASTE FROM LEFT






//CHECK IF STATE RIGHT0
drawRIGHT0:
LOAD R5 R3
CMPI 64 r5
BNE drawRIGHT1	//else check if in state RIGHT1
//check the condition of the mouth

//if open
CMPI 1 R4
BNE CLOSED_STATE_RIGHT0
//load PMANOPEN_RIGHT_0
//GLYPH 245
MOVI 245 R1
STOR r1 r0 
ADDI 1 r0	//get location TO THE LEFT
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

CLOSED_STATE_RIGHT0:
LUI 0 r1	//load PMANCLOSED_RIGHT_0
// GLYPH 205
MOVI 205 R1 
STOR r1 r0
ADDI 1 r0	//get location TO THE LEFT
MOVI 0 r1 	//LOAD BLANK
STOR r1 r0
RETX

//CHECK IF STATE RIGHT1
drawRIGHT1:
LOAD R5 R3
CMPI 65 r5

BNE drawRIGHT2 //else check if in state RIGHT2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4

BNE CLOSED_STATE_RIGHT1
//GET PMANOPEN_Right_1...in GLYPH 246
MOVI 246 r1
STOR R1 R0	//LOAD POSITION
ADDI -1 R0 	// GET POSITION TO THE RIGHT OF PACMAN
//NOW NEED TO PMANOPEN_Right_2
//ITS IN LOCATION 247
MOVI 247 R1
STOR r1 r0	//STORE POSITION BELOW PACMAN
RETX

CLOSED_STATE_RIGHT1:
//LOAD PMANCLOSED_Right_1
//IT'S GLYPH 206
MOVI 206 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI -1 R0 	// GET POSITION TO THE RIGHT OF PACMAN
//NOW NEED TO LOAD PMANCLOSED_Right_2
//IT'S GLYPH 207
MOVI 207 R1
STOR R1 R0 //LOAD INTO POSITION
RETX



//CHECK IF STATE RIGHT2
drawRIGHT2:
LOAD R5 R3
CMPI 66 r5
BNE drawRIGHT3 //else check if in state RIGHT2
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_RIGHT2
//GET PMANOPEN_Right_3
//THIS IS GLYPH 248
MOVI 248 r1
STOR R1 R0	//LOAD POSITION
ADDI -1 R0 // GET POSITION TO THE RIGHT OF PACMAN
//NOW NEED TO LOAD PMANOPEN_Right_4
//ITS IN LOCATION 249
MOVI 249 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_RIGHT2:
//LOAD PMANCLOSED_Right_3
//IT'S GLYPH 208
MOVI 208 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI -1 R0 // GET POSITION TO THE RIGHT PACMAN
//NOW NEED TO LOAD PMANCLOSED_Right_4
//IT'S GLYPH 209
MOVI 209 R1
STOR R1 R0 //LOAD INTO POSITION
RETX

//CHECK IF STATE RIGHT3
drawRIGHT3:
LOAD R5 R3
CMPI 67 r5
BNE drawDEAD1 //else check if in state drawRIGHT0
//CHECK CONDITION OF MOUTH
//IF OPEN
CMPI 1 R4
BNE CLOSED_STATE_RIGHT3
//GET PMANOPEN_Right_6
//THIS IS GLYPH 251
MOVI 251 r1
STOR R1 R0	//LOAD POSITION
ADDI 1 R0 	// GET POSITION TO THE LEFT OF PACMAN
//NOW NEED TO PMANOPEN_Right_5
//ITS IN LOCATION 250
MOVI 250 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX

CLOSED_STATE_RIGHT3:
//LOAD PMANCLOSED_Right_6
//IT'S GLYPH 211
MOVI 211 R1
STOR R1 R0 //LOAD INTO POSITION
ADDI 1 R0 // GET POSITION TO THE LEFT PACMAN
//NOW NEED TO LOAD PMANCLOSED_Right_5 (SAME AS PMANCLOSED)
//IT'S GLYPH 210
MOVI 210 R1
STOR r1 r0	//STORE POSITION ABOVE PACMAN
RETX


drawDEAD0:
ADD r0 r0