//TEST PACMAN PRESETN STATE TIMER
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 243 R1
MOVI 1  R2
STOR R2 R1

//TEST ARI GHOST present state change timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 241 R1
MOVI 1 R2
STOR R2 R1

//TEST ZACH GHOST present state change timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 239 R1
MOVI 1 R2
STOR R2 R1

//TEST JEFF GHOST present state change timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1 
ORI 237 R1
MOVI 1 R2
STOR R2 R1


//TEST TODD GHOST present state change timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 235 R1
MOVI 1 R2
STOR R2 R1

//TEST TODD GHOST present state change timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 233 R1
MOVI 1 R2
STOR R2 R1

//TEST PACMAN OPEN/CLOSED timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 231 R1
MOVI 1 R2
STOR R2 R1


//TEST GHOST FLASH WHEN EDIBLE timer
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 229 R1 
MOVI 1 R2
STOR R2 R1

//TEST SCATTER MODE
//TEST ADDRESS OF PACMAN STATE CHANGER
LUI 255 R1
ORI 227 R1
MOVI 1 R2
STOR R2 R1


//halt code
//CMPI 1 R2
BEQ 0











